# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, value: str=None, output: str=None, logurl: str=None):  # noqa: E501
        """ApiResponse - a model defined in Swagger

        :param code: The code of this ApiResponse.  # noqa: E501
        :type code: int
        :param value: The value of this ApiResponse.  # noqa: E501
        :type value: str
        :param output: The output of this ApiResponse.  # noqa: E501
        :type output: str
        :param logurl: The logurl of this ApiResponse.  # noqa: E501
        :type logurl: str
        """
        self.swagger_types = {
            'code': int,
            'value': str,
            'output': str,
            'logurl': str
        }

        self.attribute_map = {
            'code': 'code',
            'value': 'value',
            'output': 'output',
            'logurl': 'logurl'
        }
        self._code = code
        self._value = value
        self._output = output
        self._logurl = logurl

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponse of this ApiResponse.  # noqa: E501
        :rtype: ApiResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ApiResponse.


        :return: The code of this ApiResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ApiResponse.


        :param code: The code of this ApiResponse.
        :type code: int
        """

        self._code = code

    @property
    def value(self) -> str:
        """Gets the value of this ApiResponse.


        :return: The value of this ApiResponse.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ApiResponse.


        :param value: The value of this ApiResponse.
        :type value: str
        """

        self._value = value

    @property
    def output(self) -> str:
        """Gets the output of this ApiResponse.


        :return: The output of this ApiResponse.
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output: str):
        """Sets the output of this ApiResponse.


        :param output: The output of this ApiResponse.
        :type output: str
        """

        self._output = output

    @property
    def logurl(self) -> str:
        """Gets the logurl of this ApiResponse.


        :return: The logurl of this ApiResponse.
        :rtype: str
        """
        return self._logurl

    @logurl.setter
    def logurl(self, logurl: str):
        """Sets the logurl of this ApiResponse.


        :param logurl: The logurl of this ApiResponse.
        :type logurl: str
        """

        self._logurl = logurl
