# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Userkey(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: str=None, pubkey: str=None):  # noqa: E501
        """Userkey - a model defined in Swagger

        :param user: The user of this Userkey.  # noqa: E501
        :type user: str
        :param pubkey: The pubkey of this Userkey.  # noqa: E501
        :type pubkey: str
        """
        self.swagger_types = {
            'user': str,
            'pubkey': str
        }

        self.attribute_map = {
            'user': 'user',
            'pubkey': 'pubkey'
        }
        self._user = user
        self._pubkey = pubkey

    @classmethod
    def from_dict(cls, dikt) -> 'Userkey':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Userkey of this Userkey.  # noqa: E501
        :rtype: Userkey
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this Userkey.


        :return: The user of this Userkey.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this Userkey.


        :param user: The user of this Userkey.
        :type user: str
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def pubkey(self) -> str:
        """Gets the pubkey of this Userkey.


        :return: The pubkey of this Userkey.
        :rtype: str
        """
        return self._pubkey

    @pubkey.setter
    def pubkey(self, pubkey: str):
        """Sets the pubkey of this Userkey.


        :param pubkey: The pubkey of this Userkey.
        :type pubkey: str
        """

        self._pubkey = pubkey
